import { Body, Controller, Delete, Get, HttpCode, HttpStatus, Param, Patch, Post, Req, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiCreatedResponse, ApiNoContentResponse, ApiProperty, ApiPropertyOptional, ApiTags } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsBoolean, IsInt, IsOptional, IsString, Length, Min } from 'class-validator';
import { Roles } from '../../auth/decorators/roles.decorator.js';
import { FirebaseAuthGuard, type AuthenticatedRequest } from '../../auth/guards/firebase-auth.guard.js';
import { RolesGuard } from '../../auth/guards/roles.guard.js';
import { SkusService, type SkuResponse } from './skus.service.js';
class SkuDto { @ApiPropertyOptional() @IsOptional() @IsString() @Length(1, 80) code?: string; @ApiPropertyOptional() @IsOptional() @IsString() @Length(1, 80) barcode?: string; @ApiProperty() @Type(() => Number) @IsInt() @Min(1) priceAmount!: number; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) compareAtAmount?: number; @ApiPropertyOptional({ default: 'THB' }) @IsOptional() @IsString() @Length(3, 3) currency?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) weightGrams?: number; @ApiPropertyOptional() @IsOptional() @IsBoolean() isActive?: boolean; }
@ApiTags('catalog/skus') @Controller('seller/products/:productId/variants/:variantId/skus') @UseGuards(FirebaseAuthGuard, RolesGuard) @Roles('SELLER') @ApiBearerAuth()
export class SkusController { constructor(private readonly service: SkusService) {} @Get() list(@Req() r: AuthenticatedRequest, @Param('productId') p: string, @Param('variantId') v: string): Promise<SkuResponse[]> { return this.service.list(r.user!, p, v); } @Post() @ApiCreatedResponse() create(@Req() r: AuthenticatedRequest, @Param('productId') p: string, @Param('variantId') v: string, @Body() d: SkuDto): Promise<SkuResponse> { return this.service.create(r.user!, p, v, d); } @Patch(':id') update(@Req() r: AuthenticatedRequest, @Param('productId') p: string, @Param('variantId') v: string, @Param('id') id: string, @Body() d: Partial<SkuDto>): Promise<SkuResponse> { return this.service.update(r.user!, p, v, id, d); } @Delete(':id') @HttpCode(HttpStatus.NO_CONTENT) @ApiNoContentResponse() async remove(@Req() r: AuthenticatedRequest, @Param('productId') p: string, @Param('variantId') v: string, @Param('id') id: string): Promise<void> { await this.service.remove(r.user!, p, v, id); } }
