import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import { IsArray, IsEnum, IsIn, IsNotEmpty, IsObject, IsOptional, IsString, IsUUID, Matches, MaxLength } from 'class-validator';
import { PaginationDto } from '../../dto/pagination.dto.js';
export const PRODUCT_STATUSES = ['DRAFT', 'ACTIVE', 'ARCHIVED'] as const;
export type ProductStatus = (typeof PRODUCT_STATUSES)[number];
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export class CreateProductDto { @ApiProperty() @IsString() @IsNotEmpty() @MaxLength(180) name!: string; @ApiProperty({ pattern: SLUG.source }) @IsString() @Matches(SLUG) @MaxLength(200) slug!: string; @ApiPropertyOptional({ format: 'uuid' }) @IsOptional() @IsUUID() categoryId?: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(10000) description?: string; @ApiPropertyOptional({ type: [Object] }) @IsOptional() @IsArray() @IsObject({ each: true }) media?: Record<string, unknown>[]; @ApiPropertyOptional({ enum: PRODUCT_STATUSES, default: 'DRAFT' }) @IsOptional() @IsEnum(PRODUCT_STATUSES) status: ProductStatus = 'DRAFT'; }
export class UpdateProductDto { @ApiPropertyOptional() @IsOptional() @IsString() @IsNotEmpty() @MaxLength(180) name?: string; @ApiPropertyOptional({ pattern: SLUG.source }) @IsOptional() @IsString() @Matches(SLUG) @MaxLength(200) slug?: string; @ApiPropertyOptional({ format: 'uuid', nullable: true }) @IsOptional() @IsUUID() categoryId?: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(10000) description?: string; @ApiPropertyOptional({ type: [Object] }) @IsOptional() @IsArray() @IsObject({ each: true }) media?: Record<string, unknown>[]; @ApiPropertyOptional({ enum: PRODUCT_STATUSES }) @IsOptional() @IsEnum(PRODUCT_STATUSES) status?: ProductStatus; }
export class ProductQueryDto extends PaginationDto { @ApiPropertyOptional({ format: 'uuid' }) @IsOptional() @IsUUID() categoryId?: string; @ApiPropertyOptional({ enum: PRODUCT_STATUSES }) @IsOptional() @IsEnum(PRODUCT_STATUSES) status?: ProductStatus; @ApiPropertyOptional() @IsOptional() @IsString() @Transform(({ value }) => typeof value === 'string' ? value.trim() : value) search?: string; @ApiPropertyOptional({ enum: ['name', 'createdAt', 'publishedAt'], default: 'createdAt' }) @IsOptional() @IsIn(['name', 'createdAt', 'publishedAt']) sortBy: 'name' | 'createdAt' | 'publishedAt' = 'createdAt'; @ApiPropertyOptional({ enum: ['asc', 'desc'], default: 'desc' }) @IsOptional() @IsIn(['asc', 'desc']) sortOrder: 'asc' | 'desc' = 'desc'; }
export class ProductResponseDto { @ApiProperty() id!: string; @ApiProperty() sellerId!: string; @ApiProperty({ nullable: true }) categoryId!: string | null; @ApiProperty() name!: string; @ApiProperty() slug!: string; @ApiProperty({ nullable: true }) description!: string | null; @ApiProperty({ enum: PRODUCT_STATUSES }) status!: ProductStatus; @ApiProperty({ nullable: true }) media!: unknown; @ApiProperty({ nullable: true }) publishedAt!: string | null; @ApiProperty() createdAt!: string; @ApiProperty() updatedAt!: string; }
