import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { PrismaService } from '../../../../database/prisma.service.js';
import type { ProductQueryDto, ProductStatus } from '../dto/product.dto.js';
export type ProductRecord = { id: string; sellerId: string; categoryId: string | null; name: string; slug: string; description: string | null; media: Record<string, unknown>[] | null; status: ProductStatus; publishedAt: Date | null; createdAt: Date; updatedAt: Date };
@Injectable() export class ProductsRepository {
  constructor(private readonly prisma: PrismaService) {}
  async findSellerId(userId: string): Promise<string | null> { const rows = await this.prisma.$queryRaw<{ id: string }[]>`SELECT "id" FROM "Seller" WHERE "userId" = ${userId}::uuid AND "status" = 'ACTIVE'::"SellerStatus" LIMIT 1`; return rows[0]?.id ?? null; }
  async create(sellerId: string, input: CreateInput): Promise<ProductRecord> { const rows = await this.prisma.$queryRaw<ProductRecord[]>`INSERT INTO "Product" ("id","sellerId","categoryId","name","slug","description","media","status","publishedAt","createdAt","updatedAt") VALUES (${randomUUID()}::uuid,${sellerId}::uuid,${input.categoryId ?? null}::uuid,${input.name},${input.slug},${input.description ?? null},${input.media ? JSON.stringify(input.media) : null}::jsonb,${input.status}::"ProductStatus",${input.status === 'ACTIVE' ? new Date() : null},NOW(),NOW()) RETURNING "id","sellerId","categoryId","name","slug","description","media","status","publishedAt","createdAt","updatedAt"`; return rows[0]!; }
  async findById(id: string): Promise<ProductRecord | null> { const rows = await this.prisma.$queryRaw<ProductRecord[]>`SELECT "id","sellerId","categoryId","name","slug","description","media","status","publishedAt","createdAt","updatedAt" FROM "Product" WHERE "id"=${id}::uuid LIMIT 1`; return rows[0] ?? null; }
  async list(query: ProductQueryDto, sellerId?: string, publicOnly = false): Promise<{items: ProductRecord[];total:number}> { const offset=(query.page-1)*query.pageSize; const column=query.sortBy==='name'?'"name"':query.sortBy==='publishedAt'?'"publishedAt"':'"createdAt"'; const direction=query.sortOrder==='asc'?'ASC':'DESC'; const sql=`SELECT "id","sellerId","categoryId","name","slug","description","media","status","publishedAt","createdAt","updatedAt",COUNT(*) OVER() AS total FROM "Product" WHERE ($1::uuid IS NULL OR "sellerId"=$1::uuid) AND ($2::uuid IS NULL OR "categoryId"=$2::uuid) AND ($3::"ProductStatus" IS NULL OR "status"=$3::"ProductStatus") AND ($4::text IS NULL OR "name" ILIKE $5) ${publicOnly ? `AND "status"='ACTIVE'::"ProductStatus"` : ''} ORDER BY ${column} ${direction}, "id" ASC LIMIT $6 OFFSET $7`; const rows=await this.prisma.$queryRawUnsafe<(ProductRecord & {total:bigint})[]>(sql,sellerId ?? null,query.categoryId ?? null,query.status ?? null,query.search ?? null,query.search ? `%${query.search}%` : null,query.pageSize,offset); return {items:rows,total:Number(rows[0]?.total ?? 0n)}; }
  async update(id: string, input: Partial<CreateInput>): Promise<ProductRecord> { const rows=await this.prisma.$queryRaw<ProductRecord[]>`UPDATE "Product" SET "categoryId"=${input.categoryId ?? null}::uuid,"name"=${input.name!},"slug"=${input.slug!},"description"=${input.description ?? null},"media"=${input.media ? JSON.stringify(input.media) : null}::jsonb,"status"=${input.status!}::"ProductStatus","publishedAt"=CASE WHEN ${input.status!}::"ProductStatus"='ACTIVE' AND "publishedAt" IS NULL THEN NOW() WHEN ${input.status!}::"ProductStatus" <> 'ACTIVE' THEN NULL ELSE "publishedAt" END,"updatedAt"=NOW() WHERE "id"=${id}::uuid RETURNING "id","sellerId","categoryId","name","slug","description","media","status","publishedAt","createdAt","updatedAt"`; return rows[0]!; }
  async categoryIsLeaf(id:string):Promise<boolean>{const rows=await this.prisma.$queryRaw<{exists:boolean}[]>`SELECT EXISTS(SELECT 1 FROM "Category" c WHERE c."id"=${id}::uuid AND NOT EXISTS(SELECT 1 FROM "Category" child WHERE child."parentId"=c."id")) AS "exists"`;return rows[0]?.exists??false;}
  async hasSku(id:string):Promise<boolean>{const rows=await this.prisma.$queryRaw<{exists:boolean}[]>`SELECT EXISTS(SELECT 1 FROM "SKU" s JOIN "Variant" v ON v."id"=s."variantId" WHERE v."productId"=${id}::uuid AND s."isActive"=true) AS "exists"`;return rows[0]?.exists??false;}
  async remove(id:string):Promise<void>{await this.prisma.$executeRaw`DELETE FROM "Product" WHERE "id"=${id}::uuid`;}
}
type CreateInput={name:string;slug:string;categoryId?:string|null;description?:string|null;media?:Record<string,unknown>[]|null;status:ProductStatus};
